POST  http://localhost:3000/register
Content-Type: application/json

{
    "nome": "USUÁRIO TESTE",
    "email": "testeusuario123@email.com",
    "senha":"senha123456789",
    "telefone": 83999999999
}
